# General Site Settings
title: Borderland Food Co.
logo: Logo-transparent_x40@2x.png
description: Providing incredible health benefits through nutritious bone broth.

# Author Settings
author:
  name: Borderland Food Company
  image: IMG_0563.jpg
  say-hello: Your Daily Dose of Health
  bio: Simple Small Batches. We ensure that our bone broth is simmered low and slow to maximize the nutrients extracted during the cooking process. 

# Contact links
facebook: https://facebook.com/borderlandfoodco
instagram: https://instagram.com/borderlandfoodco