title: Borderland Food Company
email: erica.leong@edu.sait.ca
description: >- 
  <strong>Simple Small Batches.</strong> We ensure that our bone broth is simmered low and slow to maximize the nutrients extracted during the cooking process. 
baseurl: ""
url: 'http://localhost:4000'
twitter_username: borderlandfoodco
github_username:  ericaleong

# Build settings

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
